# fly.toml app configuration file generated for ancient-morning-8801 on 2023-08-28T13:12:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-morning-8801"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
